# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/diagrammar',
                'doc_host': 'https://jsm65fenoll.github.io',
                'git_url': 'https://github.com/jsm65fenoll/diagrammar',
                'lib_path': 'diagrammar'},
  'syms': {}}
