"""A library to show grammars graphically"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/diagrammar.ipynb.

# %% auto #0
__all__ = ['n', 'Null', 'Neg', 'Node', 'End', 'Nt']

# %% ../nbs/diagrammar.ipynb
from graphviz import Digraph, Source

# %% ../nbs/diagrammar.ipynb
def n(other,**args):
    "A helper function to include grammar simbols in expressions."
    return Null._check(other,**args)

# %% ../nbs/diagrammar.ipynb
class Null():
    "Empty graph with no input nor output nodes." 
    
    count = 0  # Static variable to generate node Id's
    
    def _edgeStr(frm,to):
        return f'"{frm}" -> "{to}" ;\n'

    def _newId():
        Null.count+=1
        return str(Null.count)

    def __init__(self):
        self.inp  = set() # Id of input nodes
        self.out = set()  # Id of output nodes 
        self.content = "" # The graphviz definition of the graph
        self.nCount = 0 # Number of non-terminal nodes in the graph

    def _check(other,**args):
        '''If "other" is a string, checks if its value is defined as variable.
            Returns variable value, if defined, otherwise creates a new node with that name.
            Takes care of ' to decide node type creation.
        '''
        if isinstance(other,str):
            if isTerminal := other[0]=="'" : other=other[1:]
            if other in globals() and _expand:
                return globals()[other]
            else:
                return T(other,**args) if isTerminal else Nt(other,**args)
        else:
            return other
        
    def __and__(self,other):
        other = Null._check(other)
        result = Null()
        result.inp = self.inp
        result.out = other.out|(self.out if isinstance(other,Neg) else set())
        result.content= self.content
        for f in self.out:
            for t in other.inp:
                result.content += Null._edgeStr(f,t)
        result.content += other.content
        result.nCount=self.nCount + other.nCount
        return result

    def __or__(self,other):
        other = Null._check(other)
        result=Null()
        result.inp = self.inp|other.inp
        result.out = self.out|other.out
        result.content=self.content + other.content
        result.nCount=self.nCount + other.nCount
        return result

    __or_=__or__
    
    def __neg__(self):
        return Neg(self)

    def __pos__(self):
        for out in self.out:
            for inp in self.inp:
                self.content += Null._edgeStr(out,inp)  
        return self
     
class Neg(Null):
    def __init__(self,other):
        super().__init__()
        self.inp     = other.inp
        self.out     = other.out
        self.content = other.content

 
class Node(Null):
    
    def _nodeStr(id,label,**attrs):
        attr_str = f'label="{label}" width="0.01"'
        for k,v in attrs.items():
            attr_str += f' {k}="{v}"'
        return '"'+ id +'" ['+attr_str+'] ;\n'

    
    def __init__(self,label,shape='box',fontsize='10pt',**attrs):
        super().__init__()
        self.label = label 
        self.id = Null._newId()
        self.inp  = {self.id}
        self.out  = {self.id}
        if 'comment' in attrs:
            shape='record'
            label+="|"+attrs['comment'] 
        self.content = Node._nodeStr(self.id,label,shape=shape,fontsize=fontsize,**attrs)
        self.nCount=1



class End(Node):
    def __init__(self):
        super().__init__("",shape="circle",style="filled")

class Nt(Node):
    def __init__(self,label,**args):
        args['shape']="ellipse"
        super().__init__(label,**args)

